version: '3.8'

networks:
  gv-network:
    driver: bridge

volumes:
  prometheus_data: 
  grafana_data:
  postgres_data:

services:
  postgres:
    container_name: gestao_vagas_postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=gestao_vagas
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - gv-network

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - 9090:9090
    networks:
      - gv-network

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - gv-network

  app:
    container_name: gestao_vagas_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres:5432/gestao_vagas
      - DATABASE_USERNAME=admin
      - DATABASE_PASSWORD=admin

    depends_on:
      - postgres
    networks:
      - gv-network
